export default {
    MERGE_DATA:             'MERGE_DATA',
    INIT_BASIC:             'INIT_BASIC',
    CSS_FRAMEWORK:          'CSS_FRAMEWORK',
    CSS_GRID:               'CSS_GRID',
    CSS_TABLE:              'CSS_TABLE',
    CSS_BTN:                'CSS_BTN',
    CSS_BTNGROUP:           'CSS_BTNGROUP',
    CSS_BTNGROUP_GRID:      'CSS_BTNGROUP_GRID',
    CSS_POPMENU:            'CSS_POPMENU',
    CSS_CHECKBOXRADIO:      'CSS_CHECKBOXRADIO',
    CSS_TABS:               'CSS_TABS',
    CSS_TABS_POPMENU:       'CSS_TABS_POPMENU',
    CSS_TAG:                'CSS_TAG',
    CSS_INPUT:              'CSS_INPUT',
    CSS_INPUTGROUP:         'CSS_INPUTGROUP',
    CSS_FORM:               'CSS_FORM',
    CSS_MASK:               'CSS_MASK',
    CSS_DLG:                'CSS_DLG',
    CSS_COMMCLASS:          'CSS_COMMCLASS'
};